In [1]:
import numpy as np
import open3d as o3d
import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D

In [8]:
print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("test.ply")
print(pcd)

Load a ply point cloud, print it, and render it
geometry::PointCloud with 14444 points.


In [ ]:
#display point cloud
o3d.visualization.draw_geometries([pcd])

In [ ]:
o3d.io.write_point_cloud('cue.pcd',pcd)

In [ ]:
#access data
data = np.asarray(pcd.points)

In [ ]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd])

In [ ]:
print("Recompute the normal of the downsampled point cloud")
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(
    radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd])

In [ ]:
print("Print the normal vectors of the first 10 points")
print(np.asarray(downpcd.normals)[:10, :])

In [11]:
#read mesh
mesh = o3d.io.read_triangle_mesh("./Mesh/results/gaussian_pose_4.ply")

In [12]:
print("Computing normal and rendering it.")
mesh.compute_vertex_normals()
print(np.asarray(mesh.triangle_normals))
o3d.visualization.draw_geometries([mesh])

Computing normal and rendering it.
[[-0.168449   -0.59572026  0.78532943]
 [-0.19204621 -0.77102543  0.60715569]
 [-0.20174553  0.06043757  0.9775715 ]
 ...
 [ 0.14690474 -0.31582063  0.93737737]
 [ 0.23421566 -0.15322812  0.96003342]
 [ 0.23444011 -0.1529908   0.96001648]]
